version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    ports:
            - "8080:80"
    environment:
            PGADMIN_DEFAULT_EMAIL: dev@stkcommand.com
            PGADMIN_DEFAULT_PASSWORD: blahblah